### ISSUE TITLE
EPIC - PgDay 2017 (WIP)

### ISSUE THREAD

**Issue by allustin** [VanessaDockers/pgsteroids#16]
## Зона 1С:
- [x] "Драка за запись" - умирающие таблицы
- [x] "Всё до сЕбе" - Недопроектированная информационная система
- [x] "Эргономисты блин" - Иерархические справочники
- [x] "Дайте больше серваков" - Системно-пользовательские таблицы
- [x] etc

Все примеры должны быть в каталоге скриптов
Проблемы выявляются pgHero, powa и pgBadger
## Зона PG
- [x] "Ленинградское время 0 часов 0 минут" - недостаток оборудования
- [x] Checkpoints
- [x] WAL Writers
- [x] etc

проблемы покажет pgBadger
## Дополнительно:
- [x] SELECT \* FROM \* штатной УТ 11
- [x] SELECT \* FROM \* штатной БП 3.0
- [x] SELECT \* FROM \* штатной ЗУП 3.0

**Comment by allustin** [comment]
Задача собственно была выполнена - но...

**Comment by allustin** [comment]
Актуализировать доклад и выступить в 2017  в виде tutorial.
tutorial положить в Git $-)

**Comment by allustin** [comment]
Так заявка согласовано - стартуем EPIC

**Comment by allustin** [comment]
Финально готов
