### ISSUE TITLE
EPIC Рефакторинг ;-)

### ISSUE THREAD

**Issue by allustin** [VanessaDockers/pgsteroids#18]
3 цели:

- [ ] скрипты переделать на oscript
- [ ] сделать 2 режима - контрибьютор и пользователь
- [ ] отказаться от Vagrant, попробовать по крайней мере

картинка для привлечения внимания по третьему пункту

![image](https://cloud.githubusercontent.com/assets/55323/15450392/f42d5034-1fa2-11e6-9ce9-80dc7c5a235e.png)
